// Code generated by protoc-gen-go.
// source: book.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	book.proto

It has these top-level messages:
	Book
*/
package main

import proto "code.google.com/p/goprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Book struct {
	BookId           *string `protobuf:"bytes,3,req,name=book_id" json:"book_id,omitempty"`
	Title            *string `protobuf:"bytes,1,req,name=title" json:"title,omitempty"`
	PageCount        *int32  `protobuf:"varint,2,req,name=page_count" json:"page_count,omitempty"`
	AuthorName       *string `protobuf:"bytes,4,req,name=author_name" json:"author_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}

func (m *Book) GetBookId() string {
	if m != nil && m.BookId != nil {
		return *m.BookId
	}
	return ""
}

func (m *Book) GetTitle() string {
	if m != nil && m.Title != nil {
		return *m.Title
	}
	return ""
}

func (m *Book) GetPageCount() int32 {
	if m != nil && m.PageCount != nil {
		return *m.PageCount
	}
	return 0
}

func (m *Book) GetAuthorName() string {
	if m != nil && m.AuthorName != nil {
		return *m.AuthorName
	}
	return ""
}

func init() {
}
